# fly.toml app configuration file generated for tip-calculator on 2023-07-15T15:55:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tip-calculator"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
